/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;
import Business.Person;
import Business.personDirectory;
import Business.userDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.User;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class adminMenuJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    //private AccountDirectory accountDirectory;
    private personDirectory persondirectory;
    private userDirectory userdirectory;
    
    
    
    adminMenuJPanel(JPanel userProcessContainer, personDirectory persondirectory, userDirectory userdirectory) {
        
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.persondirectory = persondirectory;
        this.userdirectory = userdirectory;
        populateTable();
        
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNUID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersons = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnCreatePerson = new javax.swing.JButton();
        btnManagePerson = new javax.swing.JButton();
        lblUserLoginMenu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        tblPersons.setBackground(new java.awt.Color(255, 204, 153));
        tblPersons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "UserID", "NUID", "Username", "Password", "First Name", "Last Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPersons);

        btnSearch.setBackground(new java.awt.Color(255, 204, 153));
        btnSearch.setText("Search Person by NUID");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCreatePerson.setBackground(new java.awt.Color(255, 204, 153));
        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnManagePerson.setBackground(new java.awt.Color(255, 204, 153));
        btnManagePerson.setText("Manage Person");
        btnManagePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonActionPerformed(evt);
            }
        });

        lblUserLoginMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblUserLoginMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserLoginMenu.setText("Admin Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnManagePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(lblUserLoginMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblUserLoginMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManagePerson)
                .addGap(206, 206, 206))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
           Person result = persondirectory.searchPerson(txtNUID.getText());
     if(result == null){
         
         JOptionPane.showMessageDialog(null,"Person doesn't exist","Information",JOptionPane.INFORMATION_MESSAGE);
         
                
         
     }
     
     else{
         
         managePersonJPanel panel = new managePersonJPanel(userProcessContainer,persondirectory,userdirectory,result);
         userProcessContainer.add("managePersonJPanel",panel);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);
         
     }
     
        
    }//GEN-LAST:event_btnSearchActionPerformed

   
    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        
        createPersonJPanel panel = new createPersonJPanel(userProcessContainer,persondirectory,userdirectory);
        userProcessContainer.add("createPersonJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        
    }
    

 /*       int selectedRow = tblPersons.getSelectedRow();
        if(selectedRow < 0 ){

            JOptionPane.showMessageDialog(null,"Please select a row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);

        }

        else {

            Account account = (Account)tblPersons.getValueAt(selectedRow,0);
            ViewAccountJPanel panel = new ViewAccountJPanel(userProcessContainer,account);
            userProcessContainer.add("ViewAccountJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }

        }
*/
    private void populateTable() {

 /*           //System.out.println(report);
            int count=0;
            System.out.println("Populate Table");
            System.out.println(count);
            count=count+1;
            for(Person person: persondirectory.getpersonList()){
                System.out.println(person.getUserId());
                System.out.println(person.getFirstName());
                System.out.println(person.getLastName());
                System.out.println(person.getEmail());
                System.out.println(person.getUsername());
                System.out.println(person.getPassword());
            }
   */          
            DefaultTableModel dtm = (DefaultTableModel) tblPersons.getModel();
            dtm.setRowCount(0);
            for(Person person: persondirectory.getpersonList()){
                System.out.println(person);
                Object[] row = new Object[8];
                row[0] = person;
                row[1] = person.getNUID();
                row[2] = person.getUsername();
                row[3] = person.getPassword();
                row[4] = person.getFirstName();
                row[5] = person.getLastName();
                row[6] = person.getEmail();
                //row[7] = 

                dtm.addRow(row);
                
            }

        }

  
/*  
        // Variables declaration - do not modify
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnManagePerson;
        private javax.swing.JButton btnSearch;
        private javax.swing.JButton btnCreatePerson;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tblPersons;
        private javax.swing.JTextField txtAccountNumber;
        // End of variables declaration

        private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:

            Account result = accountDirectory.searchAccount(txtAccountNumber.getText());
            if(result == null){

                JOptionPane.showMessageDialog(null,"Account Number doesn't exist","Information",JOptionPane.INFORMATION_MESSAGE);

            }

            else{

                ViewAccountJPanel panel = new ViewAccountJPanel(userProcessContainer,result);
                userProcessContainer.add("ViewAccountJPanel",panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            }

        }
        



        


        
    }//GEN-LAST:event_btnCreatePersonActionPerformed
*/
    private void btnManagePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblPersons.getSelectedRow();
        if(selectedRow < 0 ){
            
            JOptionPane.showMessageDialog(null,"Please select a row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);
                
            }
            
        
        
        else {
    
        Person person = (Person)tblPersons.getValueAt(selectedRow,0);
        managePersonJPanel panel = new managePersonJPanel(userProcessContainer,persondirectory,userdirectory,person);
        userProcessContainer.add("managePersonJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
            
            
        }
    }//GEN-LAST:event_btnManagePersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnManagePerson;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUserLoginMenu;
    private javax.swing.JTable tblPersons;
    private javax.swing.JTextField txtNUID;
    // End of variables declaration//GEN-END:variables
}
