/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;
import Business.Person;
import Business.User;
import Business.personDirectory;
import Business.userDirectory;
import java.awt.CardLayout;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.passwordHashing;
/**
 *
 * @author mac
 */
public class changePasswordJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    //private AccountDirectory accountDirectory;
    private personDirectory persondirectory;
    private userDirectory userdirectory;
    private User current_user;
    private String password_checker;
    boolean password_checking;
    /**
     * Creates new form changePasswordJPanel
     */

    changePasswordJPanel(JPanel userProcessContainer, personDirectory persondirectory, userDirectory userdirectory, User current_user) {
          initComponents();
        this.userProcessContainer = userProcessContainer;
        this.persondirectory = persondirectory;
        this.userdirectory = userdirectory;
        this.current_user = current_user;
        
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewPassword = new javax.swing.JLabel();
        lblPasswordMenu = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JTextField();
        btnNewPasswordSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        lblNewPassword.setText("New Password:");

        lblPasswordMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPasswordMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasswordMenu.setText("Change Password Menu");

        btnNewPasswordSubmit.setBackground(new java.awt.Color(255, 204, 153));
        btnNewPasswordSubmit.setText("Submit");
        btnNewPasswordSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPasswordSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(lblNewPassword)
                        .addGap(60, 60, 60)
                        .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(lblPasswordMenu)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNewPasswordSubmit)
                .addGap(405, 405, 405))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblPasswordMenu)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPassword)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addComponent(btnNewPasswordSubmit)
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewPasswordSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPasswordSubmitActionPerformed
        // TODO add your handling code here:
        
        password_checker=txtNewPassword.getText();
        password_checking = passwordHashing.logincheck(current_user.getUser_Username(),password_checker);
        if(password_checking==false)
        {
            JOptionPane.showMessageDialog(null,"Password matching a previous password, please try a different one","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Password updated","Information",JOptionPane.INFORMATION_MESSAGE);
            current_user.setUser_Password(password_checker);
               for(Person person: persondirectory.personList)
                {
                   if(person.getNUID().equals(current_user.getUser_NUID())){
                       
                      
                       person.setPassword(password_checker);
                       
                       
                       
                   } 
                }
        }
        
        
    }//GEN-LAST:event_btnNewPasswordSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewPasswordSubmit;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblPasswordMenu;
    private javax.swing.JTextField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
