/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;
import Business.Person;
import Business.User;
import Business.personDirectory;
import Business.userDirectory;
import java.awt.CardLayout;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.passwordHashing;



/**
 *
 * @author mac
 */
public class userMenuJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    //private AccountDirectory accountDirectory;
    private personDirectory persondirectory;
    private userDirectory userdirectory;
    private User current_user;
    private int changePasswordSwitch=0; //to toggle between save and change pass button
    private String buffer_password; //if password doesn't pass the critera it will be used to revert back to old password
    /**
     * Creates new form userMenuJPanel
     */
    
    
    userMenuJPanel(JPanel userProcessContainer, personDirectory persondirectory, userDirectory userdirectory, User current_user) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.persondirectory = persondirectory;
        this.userdirectory = userdirectory;
        this.current_user = current_user;
        buffer_password=current_user.getUser_Password();
        populateCurrentUserDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSaveUserDetails = new javax.swing.JButton();
        btnUpdateUserDetails = new javax.swing.JButton();
        txtDisplayUserID = new javax.swing.JTextField();
        txtDisplayNUID = new javax.swing.JTextField();
        txtDisplayUsername = new javax.swing.JTextField();
        txtDisplayPassword = new javax.swing.JTextField();
        btnChangePassword = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Menu");

        jLabel2.setText("UserID:");

        jLabel3.setText("NUID:");

        jLabel4.setText("Username:");

        jLabel5.setText("Password:");

        btnSaveUserDetails.setBackground(new java.awt.Color(255, 204, 153));
        btnSaveUserDetails.setText("Save");
        btnSaveUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUserDetailsActionPerformed(evt);
            }
        });

        btnUpdateUserDetails.setBackground(new java.awt.Color(255, 204, 153));
        btnUpdateUserDetails.setText("Update");
        btnUpdateUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserDetailsActionPerformed(evt);
            }
        });

        txtDisplayUserID.setEnabled(false);

        txtDisplayNUID.setEnabled(false);

        txtDisplayUsername.setEnabled(false);

        txtDisplayPassword.setEditable(false);
        txtDisplayPassword.setText("**************");
        txtDisplayPassword.setEnabled(false);
        txtDisplayPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayPasswordActionPerformed(evt);
            }
        });

        btnChangePassword.setBackground(new java.awt.Color(255, 204, 153));
        btnChangePassword.setText("Change Password?");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDisplayNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDisplayUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDisplayPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnSaveUserDetails)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnUpdateUserDetails))))))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDisplayUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDisplayNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDisplayPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveUserDetails)
                    .addComponent(btnUpdateUserDetails))
                .addGap(18, 18, 18)
                .addComponent(btnChangePassword)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserDetailsActionPerformed
        // TODO add your handling code here:
        
        btnSaveUserDetails.setEnabled(true);
        btnUpdateUserDetails.setEnabled(false);
        
        txtDisplayUserID.setEnabled(true);
        //txtDisplayPassword.setEnabled(true);
        txtDisplayUsername.setEnabled(true);
        //txtDisplayNUID.setEnabled(true);
        
        
    }//GEN-LAST:event_btnUpdateUserDetailsActionPerformed

    private void btnSaveUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserDetailsActionPerformed
        // TODO add your handling code here:
      /*  
        btnSaveUserDetails.setEnabled(false);
        btnUpdateUserDetails.setEnabled(true);
        if(changePasswordSwitch==1)
        {
          if(passwordHashing.loginUser(txtDisplayUsername.getText(),txtDisplayPassword.getText())==false)
        {
            JOptionPane.showMessageDialog(null,"Password matching a previous password, please try a different one","Information",JOptionPane.INFORMATION_MESSAGE);
        }
          else{
              JOptionPane.showMessageDialog(null,"Password updated","Information",JOptionPane.INFORMATION_MESSAGE);
              current_user.setUser_Password(txtDisplayPassword.getText());
          }
        }
        else {
        */
        current_user.setUser_NUID(txtDisplayNUID.getText());
        
        //current_user.setUser_Password(txtDisplayPassword.getText());
        current_user.setUser_UserId(txtDisplayUserID.getText());
        
        for (passwordHashing.UserPasswordHistory user : passwordHashing.usernameList) {
        if (user.username.equals(current_user.getUser_Username())) {
            user.username=txtDisplayUsername.getText();
            current_user.setUser_Username(txtDisplayUsername.getText()); 
        }
        
              System.out.println("after save button");
    
      
                System.out.println(current_user.getUser_Username());
                System.out.println(current_user.getUser_Password());
                System.out.println(current_user.getUser_NUID());
                System.out.println(current_user.getUser_UserId());
        
                
               User check = userdirectory.searchUserUpdated(current_user);
               System.out.println("after checking searchuserupdated");
                System.out.println(check.getUser_Username());
                System.out.println(check.getUser_Password());
                System.out.println(check.getUser_NUID());
                System.out.println(check.getUser_UserId());
               
                for(Person person: persondirectory.personList)
                {
                   if(person.getNUID().equals(current_user.getUser_NUID())){
                       person.setUsername(current_user.getUser_Username());
                      
                       person.setPassword(current_user.getUser_Password());
                       
                       person.setUserId(current_user.getUser_UserId());
                       
                   } 
                }
            
                
        
        
        
         //txtDisplayPassword.setEnabled(false);
        //txtDisplayPassword.setEditable(false);
        btnSaveUserDetails.setEnabled(false);
        btnUpdateUserDetails.setEnabled(true);
        }   
    }//GEN-LAST:event_btnSaveUserDetailsActionPerformed

    private void txtDisplayPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayPasswordActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null,"Going to Change Password Page","Information",JOptionPane.INFORMATION_MESSAGE);
            changePasswordJPanel panel = new changePasswordJPanel(userProcessContainer,persondirectory,userdirectory,current_user);
            userProcessContainer.add("changePasswordJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_btnChangePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnSaveUserDetails;
    private javax.swing.JButton btnUpdateUserDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDisplayNUID;
    private javax.swing.JTextField txtDisplayPassword;
    private javax.swing.JTextField txtDisplayUserID;
    private javax.swing.JTextField txtDisplayUsername;
    // End of variables declaration//GEN-END:variables

    private void populateCurrentUserDetails() {
        
        
        
        //txtDisplayUserID.setText(current_user.getUser_UserId());
           System.out.println("Inside user menu now");
    
      
                System.out.println(current_user.getUser_Username());
                System.out.println(current_user.getUser_Password());
                System.out.println(current_user.getUser_NUID());
                System.out.println(current_user.getUser_UserId());
                
        txtDisplayPassword.setText(current_user.getUser_Password());
        txtDisplayUsername.setText(current_user.getUser_Username());
        txtDisplayNUID.setText(current_user.getUser_NUID());
        txtDisplayUserID.setText(current_user.getUser_UserId());
        
        
        btnSaveUserDetails.setEnabled(false);
        btnUpdateUserDetails.setEnabled(true);
        
        
    }
    }
